### ISSUE TITLE
I think we should refactor this function and make it a lot cleaner.

### ISSUE THREAD

**Issue by MSevey** [SkynetLabs/blocker#8]
I think we should refactor this function and make it a lot cleaner. 
I don't mind doing that I just didn't want to make too many changes to this repo.

_Originally posted by @peterjan in https://github.com/SkynetLabs/blocker/pull/7#discussion_r766757196_

**Comment by peterjan** [comment]
this is redundant as we now route block requests through nginx which now has a blocker mechanism built in
